const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const gate=$('#gate'),site=$('#site');
$('#unlock').onclick=()=>{const key=$('#d').value.padStart(2,'0')+$('#m').value.padStart(2,'0')+$('#y').value.padStart(2,'0');if(key==='241225'){gate.classList.add('open');setTimeout(()=>{gate.style.display='none';site.classList.remove('locked')},650);sessionStorage.setItem('xa25','1')}else{const c=$('.gate-card');c.classList.remove('shake');void c.offsetWidth;c.classList.add('shake');$('#gateMsg').textContent='Esa no es nuestra fecha… inténtalo otra vez ♡'}};
if(sessionStorage.getItem('xa25')==='1'){gate.style.display='none';site.classList.remove('locked')}
$$('.pin input').forEach((x,i,a)=>x.addEventListener('input',()=>{x.value=x.value.replace(/\D/g,'').slice(0,2);if(x.value.length===2&&a[i+1])a[i+1].focus()}));
const cars=[
{name:'HOT WHEELS RED',sub:'CUSTOM SUPERCAR · RED EDITION',img:'assets/cars/hw-red.png',photo:'assets/memories/01-nosotros.png',title:'Nuestro comienzo',text:'Hay recuerdos que uno guarda sin darse cuenta. Este es uno de esos: tú y yo, empezando a construir algo que hoy significa muchísimo para mí.'},
{name:'HOT WHEELS BLACK',sub:'MUSCLE · MIDNIGHT EDITION',img:'assets/cars/hw-black.png',photo:'assets/memories/06-graduacion.png',title:'Orgullosa de ti',text:'Me gusta verte crecer, cumplir metas y estar ahí para aplaudirte. Tus momentos importantes también se han vuelto recuerdos importantes para mí.'},
{name:'HOT WHEELS GREEN',sub:'CUSTOM MUSCLE · STREET EDITION',img:'assets/cars/hw-green.png',photo:'assets/memories/05-cena.png',title:'Lo simple contigo',text:'No necesito un plan enorme para pasarla bonito contigo. Una salida, una comida o una conversación cualquiera pueden terminar siendo de mis momentos favoritos.'},
{name:'GOLD SUPERCAR',sub:'GOLDEN · LIMITED EDITION',img:'assets/cars/supercar-gold.png',photo:'assets/memories/04-besito.png',title:'Mi lugar favorito',text:'Entre tantos lugares a los que podemos ir, siempre termino pensando lo mismo: mi lugar favorito es donde pueda estar cerquita de ti.'},
{name:'BLUE SUPERCAR',sub:'BLUE · PERFORMANCE EDITION',img:'assets/cars/supercar-blue.png',photo:'assets/memories/03-cusco.png',title:'Más caminos contigo',text:'Quiero seguir conociendo lugares, tomando fotos, improvisando planes y llenándonos de historias que después comiencen con un “¿te acuerdas cuando...?”'},
{name:'RED BULL F1',sub:'FORMULA · RACE EDITION',img:'assets/cars/f1-redbull.png',photo:'assets/memories/06-new.png',title:'Mi piloto favorito',text:'Este tenía que ser especial: velocidad, carreras y tú. Porque si hay alguien con quien quiero seguir recorriendo esta historia, es contigo.'}
];
const selector=$('#carSelector');cars.forEach((c,i)=>{const el=document.createElement('button');el.className='car-option'+(!i?' active':'');el.innerHTML=`<span>0${i+1}</span><img src="${c.img}" alt="${c.name}"><div><b>${c.name}</b><small>${c.sub}</small></div>`;el.onclick=()=>selectCar(i,el);selector.appendChild(el)});
function selectCar(i,el){$$('.car-option').forEach(x=>x.classList.remove('active'));el.classList.add('active');const c=cars[i],card=$('#memoryCard');card.classList.remove('flash');void card.offsetWidth;card.classList.add('flash');$('#memoryImg').src=c.photo;$('#memoryNo').textContent=`MEMORY 0${i+1}`;$('#memoryTitle').textContent=c.title;$('#memoryText').textContent=c.text}
let lane=1,playing=false,score=0,spawn;const road=$('#road'),player=$('#player');function move(dir){if(!playing)return;lane=Math.max(0,Math.min(2,lane+dir));player.style.left=['18%','50%','82%'][lane]}
$('#left').onclick=()=>move(-1);$('#right').onclick=()=>move(1);document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});let tx=null;road.addEventListener('touchstart',e=>tx=e.touches[0].clientX,{passive:true});road.addEventListener('touchend',e=>{if(tx===null)return;const d=e.changedTouches[0].clientX-tx;if(Math.abs(d)>25)move(d>0?1:-1);tx=null},{passive:true});
$('#startGame').onclick=startGame;function startGame(){road.querySelectorAll('.obstacle,.heart').forEach(x=>x.remove());playing=true;score=0;lane=1;player.style.left='50%';$('#score').textContent='0';$('#gameStatus').textContent='GO!';clearInterval(spawn);spawn=setInterval(spawnItem,720)}
function spawnItem(){if(!playing)return;const good=Math.random()>.4,el=document.createElement('div'),ln=Math.floor(Math.random()*3);el.className=good?'heart':'obstacle';el.textContent=good?'❤️':'🚧';el.style.left=['14%','46%','78%'][ln];road.appendChild(el);let y=-70;const iv=setInterval(()=>{if(!playing){clearInterval(iv);el.remove();return}y+=7;el.style.top=y+'px';const hitAt=road.clientHeight-155;if(y>hitAt&&y<hitAt+90&&ln===lane){if(good){score++;navigator.vibrate?.(35)}else{score=Math.max(0,score-1);navigator.vibrate?.([60,30,60])}$('#score').textContent=score;clearInterval(iv);el.remove();if(score>=10)win();return}if(y>road.clientHeight+20){clearInterval(iv);el.remove()}},25)}
function win(){playing=false;clearInterval(spawn);$('#gameStatus').textContent='FINISH!';setTimeout(()=>$('#secret').classList.add('show'),450)}$('#closeSecret').onclick=()=>$('#secret').classList.remove('show');
